version: "3.8"

services:
  web:
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=1
    volumes:
      - .:/home/app/code/
    ports:
      - "8000:8000"

  nginx:
    command: "true"
