# Generated by Django 3.2.4 on 2021-07-05 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('car_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doc_manager.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('units', models.CharField(choices=[('cm3', 'Cubic centimeters'), ('t', 'Tonnes')], max_length=3)),
                ('price', models.PositiveIntegerField()),
                ('from_addr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spec_from_addr', to='doc_manager.address')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_manager.material')),
                ('to_addr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spec_to_addr', to='doc_manager.address')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_manager.customer')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_manager.specification')),
            ],
            options={
                'unique_together': {('customer', 'specification')},
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='doc_manager.driver')),
                ('from_addr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ord_from_addr', to='doc_manager.address')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_manager.order')),
                ('to_addr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ord_to_addr', to='doc_manager.address')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='doc_manager.vehicle')),
            ],
        ),
    ]
