# Generated by Django 3.2.4 on 2021-07-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manager', '0003_auto_20210716_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id']},
        ),
    ]
