# Generated by Django 3.2.4 on 2021-07-17 19:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manager', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 19, 44, 56, 544705, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specification',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 17, 19, 45, 7, 685268, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specification',
            name='units',
            field=models.CharField(choices=[('m3', 'Кубические метры'), ('t', 'Тонны')], max_length=3),
        ),
    ]
