# Generated by Django 3.2.4 on 2021-07-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manager', '0006_auto_20210718_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['path_from', 'path_to'],
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='real_from_addr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='real_to_addr',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together={('from_addr', 'to_addr')},
        ),
        migrations.DeleteModel(
            name='VehicleModel',
        ),
        migrations.AddField(
            model_name='pathcost',
            name='path_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='path_from', to='doc_manager.address'),
        ),
        migrations.AddField(
            model_name='pathcost',
            name='path_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='path_to', to='doc_manager.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='doc_manager.pathcost'),
        ),
        migrations.AlterUniqueTogether(
            name='pathcost',
            unique_together={('path_from', 'path_to')},
        ),
    ]
