# Generated by Django 3.2.4 on 2021-07-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manager', '0007_auto_20210718_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=255, unique=True)),
                ('model', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['car_id'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doc_manager.driver'),
        ),
        migrations.AlterField(
            model_name='order',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doc_manager.pathcost'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doc_manager.vehiclea'),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
