# Generated by Django 3.2.4 on 2021-07-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manager', '0008_auto_20210720_1838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleA',
            new_name='Vehicle',
        ),
    ]
