# Generated by Django 3.2.4 on 2021-07-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manager', '0009_rename_vehiclea_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='order',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='specification',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
