# Generated by Django 3.2.4 on 2021-07-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manager', '0011_auto_20210725_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='doc_manager.customer'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together={('customer', 'from_addr', 'to_addr', 'material')},
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
