# Generated by Django 3.2.4 on 2021-07-29 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manager', '0012_auto_20210728_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('exec_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['exec_no'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='exec_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doc_manager.execution'),
        ),
    ]
