# Generated by Django 3.2.4 on 2021-07-30 21:00

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manager', '0016_auto_20210730_2021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pathcost',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pathcost',
            constraint=models.UniqueConstraint(fields=('path_from', 'path_to', 'contractor'), name='pathcost_unique_definition'),
        ),
        migrations.AddConstraint(
            model_name='pathcost',
            constraint=models.CheckConstraint(check=models.Q(('path_from', django.db.models.expressions.F('path_to')), _negated=True), name='pathcost_path_not_loop'),
        ),
        migrations.AddConstraint(
            model_name='specification',
            constraint=models.UniqueConstraint(fields=('customer', 'from_addr', 'to_addr', 'material', 'units'), name='specification_unique_definition'),
        ),
        migrations.AddConstraint(
            model_name='specification',
            constraint=models.CheckConstraint(check=models.Q(('from_addr', django.db.models.expressions.F('to_addr')), _negated=True), name='specification_path_not_loop'),
        ),
    ]
