# Generated by Django 3.2.4 on 2021-07-31 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('doc_manager', '0018_auto_20210731_1853'), ('doc_manager', '0019_contractorexecution_cont_exec_unique_definition')]

    dependencies = [
        ('doc_manager', '0017_auto_20210731_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_no', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_manager.contractor')),
            ],
            options={
                'ordering': ['exec_no', 'contractor'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='contr_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doc_manager.contractorexecution'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('exec_doc__isnull', True), ('contr_doc__isnull', True), _connector='OR'), name='order_not_both_docs'),
        ),
        migrations.AddConstraint(
            model_name='contractorexecution',
            constraint=models.UniqueConstraint(fields=('exec_no', 'contractor'), name='cont_exec_unique_definition'),
        ),
    ]
