# Generated by Django 3.2.4 on 2021-08-01 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manager', '0018_auto_20210731_1853_squashed_0019_contractorexecution_cont_exec_unique_definition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorexecution',
            options={'ordering': ['exec_no', 'contractor'], 'verbose_name': 'УПД подрядчика', 'verbose_name_plural': 'УПД подрядчика'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['name'], 'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ['exec_no'], 'verbose_name': 'УПД', 'verbose_name_plural': 'УПД'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name'], 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'permissions': [('undelete_order', 'Есть возможность восстанавливать заказы, помеченные на удаление'), ('hard_delete_order', 'Есть возможность удалять заказы, помеченные на удаление')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='pathcost',
            options={'ordering': ['path_from', 'path_to'], 'verbose_name': 'Путь со ставкой', 'verbose_name_plural': 'Пути со ставками'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'ordering': ['doc_no'], 'permissions': [('undelete_specification', 'Есть возможность восстанавливать спецификации, помеченные на удаление'), ('hard_delete_specification', 'Есть возможность удалять спецификации, помеченные на удаление')], 'verbose_name': 'Спецификация', 'verbose_name_plural': 'Спецификации'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['car_id'], 'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорты'},
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='order_not_both_docs',
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Полный адрес'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Подрядчик'),
        ),
        migrations.AlterField(
            model_name='contractorexecution',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_manager.contractor', verbose_name='Подрядчик'),
        ),
        migrations.AlterField(
            model_name='contractorexecution',
            name='date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contractorexecution',
            name='exec_no',
            field=models.PositiveIntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='exec_no',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contr_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doc_manager.contractorexecution', verbose_name='Номер УПД подрядчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doc_manager.contractor', verbose_name='Подрядчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doc_manager.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exec_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doc_manager.execution', verbose_name='Номер УПД'),
        ),
        migrations.AlterField(
            model_name='order',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doc_manager.pathcost', verbose_name='Путь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_manager.specification', verbose_name='Номер спец.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doc_manager.vehicle', verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='pathcost',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doc_manager.contractor', verbose_name='Подрядчик'),
        ),
        migrations.AlterField(
            model_name='pathcost',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='pathcost',
            name='path_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='path_from', to='doc_manager.address', verbose_name='Начало пути'),
        ),
        migrations.AlterField(
            model_name='pathcost',
            name='path_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='path_to', to='doc_manager.address', verbose_name='Конец пути'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_manager.customer', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='doc_no',
            field=models.PositiveIntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='from_addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spec_from_addr', to='doc_manager.address', verbose_name='Начало пути'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doc_manager.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена за ед.'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='to_addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spec_to_addr', to='doc_manager.address', verbose_name='Конец пути'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='units',
            field=models.CharField(choices=[('m3', 'м3'), ('t', 'т')], max_length=3, verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
        migrations.AddConstraint(
            model_name='specification',
            constraint=models.UniqueConstraint(fields=('doc_no', 'customer'), name='specification_unique_per_customer'),
        ),
    ]
